version: '3.8'
services:
  # Create frontend container
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    container_name: frontend-docker
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    tty: true

  # Create backend container
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    working_dir: /usr/src/app
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app/frontend
      - /usr/src/app/backend/node_modules

  # Create database container
  postgres:
    image: postgres:13-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db:${POSTGRES_DATA_DIR}
    ports:
      - "5432:5432"

# Volumes
volumes:
  postgres-db:
