version: '3.8'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
    volumes:
      - intranet-app:/frontend/
  # Create backend container
  backend:
    # Create backend container
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: always
    links:
      - db
    depends_on:
      - db
    volumes:
      - intranet-app:/backend/
  # Create database container
  db:
    image: postgres:13-alpine3.18
    container_name: database-docker
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db:${POSTGRES_DATA_DIR}
volumes:
  postgres-db:
  intranet-app: